### ISSUE TITLE
Working out rough compatibility for OpenBSD

### ISSUE THREAD

**Issue by anoduck** [m42e/zsh-histdb-skim#13]
Discovered your plugin while reworking my shell to implement [zi](https://wiki.zshell.dev), and we both have to admit, rust is pretty damn cool. So, it works nicely, there is no issue there. It just outputs an error every time my shell is loaded, `Could not find prebuild executable; Sorry, you have to do it yourself`. :confused:  To which, I always mentally respond, "I did do it myself, what is the script talking about?" :laughing:  The other thing is when I execute `histdb-skim-get-os`. I get nothing. :worried:

So, I was wondering if we could find a way to resolve these issues. 

Thanks.

**Comment by m42e** [comment]
What does `uname -a` give you?

**Comment by anoduck** [comment]
OpenBSD localhost.local 7.2 GENERIC.MP#1070 amd64

**Comment by m42e** [comment]
Hmm, I have no good solution to provide a build for openbsd. You probably want to try to build it yourself?

**Comment by m42e** [comment]
And if you already built it, take a look at the variables
```
XDG_BIN_PATH=${XDG_DATA_HOME:-$HOME/.local/share}/zsh-histdb-skim/
BIN_DIR=${HISTDB_SKIM_PATH:-${XDG_BIN_PATH}}
BIN_PATH=${BIN_DIR}/zsh-histdb-skim
```

so the script is able to find the binary

**Comment by anoduck** [comment]
@m42e I don't know what changed, but the issue seems to have resolved itself over the past two weeks. (Probably an update to zsh did the trick). It is now kicking as good as everything else, better, actually. Great plugin! Really nice. 

Thanks for working with me!

**Comment by m42e** [comment]
You're very welcome. Thanks a lot for using it.
