### ISSUE TITLE
Feature request: set default tab

### ISSUE THREAD

**Issue by RX14** [m42e/zsh-histdb-skim#17]
When pressing ctrl-r, i almost always want to search all of shell history not just a single session. Perhaps an environment variable to set the default tab, or save the last tab between opens

**Comment by m42e** [comment]
Done with #18

**Comment by RX14** [comment]
Unfortunately the musl build now segfaults for me, using archlinux. I reverted to 0.9.1 release and this feature seems to work.

**Comment by m42e** [comment]
I am sorry for that. I try something different:

- updated all deps
- try building the binary if cargo is available
- And one more thing which is not yet there: check if the binary works and if not inform the user.

would the building instead of downloading help you?

**Comment by RX14** [comment]
I get an error:
```
cargo is available, starting Rust release build
error: manifest path `/home/rx14/Cargo.toml` does not exist
```

Seems the script directory detection is not working. I am using antidote not zplug.
