### ISSUE TITLE
Commit Cargo.lock

### ISSUE THREAD

**Issue by SrTobi** [m42e/zsh-histdb-skim#2]
Just tried to build this within nix using `rustPlatform.buildRustPackage` and that failed because the `Cargo.lock` is missing.
I saw that you removed the Cargo.lock, though I don't know why. [Here](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) it is recommended to commit the Cargo.lock

**Comment by m42e** [comment]
Ok. I had that at start but sure, can do :)
I thought might not be good practice but read the last paragraph of my reader and it will explain this very much 😃

**Comment by m42e** [comment]
Added. Thanks for the hint.

**Comment by SrTobi** [comment]
Thanks! cool project
