### ISSUE TITLE
Automatic download fails when installing system-wide

### ISSUE THREAD

**Issue by oddlama** [m42e/zsh-histdb-skim#3]
First I'd like to thank you for this amazing plugin, you saved me some hours writing a proper histdb integration myself :D

I've installed this plugin system wide to `/usr/share/zsh/zsh-histdb-skim/`, which unfortunately causes my regular user to try downloading the binary to that directory. I believe it would be far better if your program would store the binary in the proper XDG directory in the user's home. So in bash/zsh syntax this would be `${XDG_DATA_HOME:-$HOME/.local/share}/zsh-histdb-skim/`.

If i'm not mistaken, the binary will also never be updated once it exists, correct? How are you planning on automatically delivering updates?

**Comment by m42e** [comment]
Added both, still you can enforce the path manually if you like.
