### ISSUE TITLE
Results are much worse than zsh-histdb-fzf

### ISSUE THREAD

**Issue by phiresky** [m42e/zsh-histdb-skim#4]
zsh-histdb-skim finds results that fit much less well first before the results I want. For example, in a search for `ls -alh` the results are:

fzf: "14/04/2022 **ls** data/artifacts/SplitDatasetArtifact **-alh**"
skim: "14/04 cargo fmt -**-al**l --features **s**qlite -- -- c**h**eck"

The reason seems to be the `.nosort(true)` option in main.rs. Removing that option, the results are much better

**Comment by m42e** [comment]
Ok, I See your point, the algorithm is different if you compare fzf with skim. 
I set the no sort to true, as I want to have the least recent result first.

We could have an option for configuration, if you want to provide a PR I would like to accept it.

**Comment by m42e** [comment]
N.B.: The search only looks at the command so you might be able to use "^ls -alh" in that particular case.

**Comment by phiresky** [comment]
>  I set the no sort to true, as I want to have the least recent result first.

That makes sense - but for me the results seem to be mostly chronological with sorting as well - i think that's because skim uses discrete ranking numbers and if the ranking is the same it uses the input (chronological) order. 

Basically from what I've seen with `nosort` it first finds tons of commands that contain any combination of the characters in the query that are not related at all (because those are more recent than the ones I'm looking for), and without `nosort` it finds 10 queries (in correct chronological order) that are pretty much what I'm looking for, then further down there's probably less good results out of order.

If you think the results are still better with nosort, would you merge a PR that adds either a configuration via env-var or a toggle that allows changing it?

**Comment by m42e** [comment]
Sure I would like to merge a PR.
Wen can also make the nosort optional. I will give a try.
